# Generated by Django 4.2.21 on 2025-05-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_bloco_alter_usuario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='apartamento',
        ),
    ]
