# Generated by Django 5.2.1 on 2025-05-28 23:51

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_chamado_apartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='chamado',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AlterModelOptions(
            name='mensagemchamado',
            options={'ordering': ['data_envio'], 'verbose_name': 'Mensagem de Chamado', 'verbose_name_plural': 'Mensagens de Chamado'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin_user',
            field=models.BooleanField(default=False, help_text='Designa se este usuário tem acesso ao painel administrativo', verbose_name='Usuário Admin'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('P', 'Proprietário'), ('I', 'Inquilino'), ('M', 'Imobiliária'), ('A', 'Administrador')], default='P', max_length=1),
        ),
    ]
