# Generated by Django 5.2.1 on 2025-05-29 00:15

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_alter_chamado_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.CreateModel(
            name='AdministradorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
    ]
