# Generated by Django 5.2.1 on 2025-05-29 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_usuario_first_name_remove_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bloco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero_apartamento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('inquilino', 'Inquilino'), ('imobiliaria', 'Imobiliária'), ('outro', 'Outro')], default='proprietario', max_length=20),
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=10)),
                ('bloco', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
