# Generated by Django 5.2.1 on 2025-05-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usuario_bloco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='quantidade_apartamentos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
