# Generated by Django 5.2.1 on 2025-05-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_quantidade_apartamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='core.apartamento'),
        ),
    ]
