# Generated by Django 4.2.21 on 2025-06-02 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comunicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='autor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'sindico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Síndico Responsável'),
        ),
    ]
