# Generated by Django 4.2.21 on 2025-06-09 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_despesa_receita_itemreceita_itemdespesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_limite', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('individual', 'Cada um vota no seu painel'), ('online', 'Reunião Online')], default='individual', max_length=20)),
                ('link_reuniao', models.URLField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('a_favor', 'A Favor'), ('contra', 'Contra')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.votacao')),
            ],
            options={
                'unique_together': {('votacao', 'usuario')},
            },
        ),
    ]
