# Generated by Django 4.2.21 on 2025-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_votacao_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='encerrada_manualmente',
            field=models.BooleanField(default=False),
        ),
    ]
